// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) 2025, spacemit Corporation.
 *
 */

#ifndef _CCU_SPACEMIT_K3_H_
#define _CCU_SPACEMIT_K3_H_

#include <clk.h>
#include <clk-uclass.h>

/* u-boot-spl would used this clk */
enum {
	CLK_PLL1_2457P6_SPL = 0,
	CLK_PLL2_SPL,
	CLK_PLL1_D3_SPL,
	CLK_PLL1_D4_SPL,
	CLK_PLL1_D5_SPL,
	CLK_PLL1_D6_SPL,
	CLK_PLL1_D8_SPL,
	CLK_PLL1_DX_SPL,
	CLK_PLL2_D5_SPL,
	CLK_PLL2_D6_SPL,
	CLK_PLL2_D8_SPL,
	//MPMU
	CLK_PLL1_307P2_SPL,
	CLK_PLL1_409P6_SPL,
	CLK_PLL1_491_SPL,
	CLK_PLL1_245P76_SPL,
	CLK_PLL1_614_SPL,
	CLK_PLL1_819_SPL,
	//APMU
	CLK_SDH_AXI_SPL,
	CLK_SDH0_SPL,
	CLK_SDH2_SPL,
	CLK_QSPI_SPL,
	CLK_QSPI_BUS_SPL,
	CLK_UFS_ACLK_SPL,
	CLK_PLL2_66_SPL,
	CLK_PLL2_33_SPL,
	CLK_PLL2_50_SPL,
	CLK_PLL2_25_SPL,
	CLK_PLL2_20_SPL,
	CLK_AXICLK_SPL,
	CLK_ESPI_SCLK_SRC_SPL,
	CLK_ESPI_SCLK_SPL,
	CLK_ESPI_MCLK_SPL,

	CLK_VCTCXO_24_SPL,
	CLK_VCTCXO_3_SPL,
	CLK_VCTCXO_1_SPL,
	CLK_PLL1_SPL,
	OSC_32K_SPL,
	CLK_DUMMY_SPL,
	CLK_MAX_NO_SPL,
};

ulong transfer_clk_id_to_spl(ulong id);

#endif /* _CCU_SPACEMIT_K3_H_ */
