# SPDX-License-Identifier: GPL-2.0
#
# Spacemit Clock specific Makefile
#
#SoC support
obj-$(CONFIG_CLK_K1_CCU)	+= k1pro-ccu.o
obj-$(CONFIG_CLK_K1_CCU)        += k1pro-pll.o

obj-$(CONFIG_SPACEMIT_K1X_CCU)     += ccu-spacemit-k1x.o ccu_pll.o ccu_ddn.o ccu_mix.o
