# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DISPLAY_SPACEMIT_INNO_DP) += inno_dp_api.o \
					  inno_dp.o \
					  inno_dp_common.o \
					  inno_edid.o \
					  inno_modes.o \
					  inno_parse_edid.o \
					  inno_utils.o
