#!/bin/sh
set -e

# returns 0 if running in chroot, 1 if not
running_in_chroot() {
    if [ "${SYSTEMD_IGNORE_CHROOT:-0}" = "1" ]; then
        return 1
    fi

    if [ -e "/proc/1/root" ]; then
        root_dev_ino=$(stat -c '%d:%i' / 2>/dev/null) || return 0
        proc1_root_dev_ino=$(stat -L -c '%d:%i' /proc/1/root 2>/dev/null) || return 0

        [ "$root_dev_ino" = "$proc1_root_dev_ino" ] && return 1 || return 0
    fi

    if [ ! -d "/proc" ] || [ ! -r "/proc/version" ]; then
        [ "$$" = "1" ] && return 1 || return 0
    fi

    return 0
}

case "$1" in
configure)
    target=""
    if grep -q 'Spacemit(R) X100' /proc/cpuinfo; then
        target="spacemit"
    else
        echo "Running not in Spacemit X100, skipping install U-Boot to bootloader partition."
        exit 0
    fi

    if running_in_chroot; then
        echo "Running in chroot, skipping install U-Boot to bootloader partition."
        exit 0
    fi

    for x in $(cat /proc/cmdline); do
        case $x in
        root=UUID=*)
            ROOT=${x#root=UUID=}
            DEVICES=$(blkid -s UUID | grep "$ROOT" | awk '{print $1}')
            DEVICE_COUNT=$(echo "$DEVICES" | wc -l)
            if [ "$DEVICE_COUNT" -gt 1 ]; then
                echo "Warning: Multiple devices found with the same UUID $ROOT:"
                echo "$DEVICES"
                echo "This may cause installation issues. Please ensure unique UUIDs."
                exit 0
            fi
            ROOT=$(echo "$DEVICES" | head -n1)
            ;;
        root=*)
            ROOT=${x#root=}
            ;;
        esac
    done

    if [ -n $ROOT ]; then
        case $ROOT in
        "/dev/mmcblk0"*)
            BOOTINFO_FILE=bootinfo_block.bin
            BOOTINFO=/dev/mmcblk0
            BOOTINFO_SEEK=$((1024 * 1024))
            FSBL=/dev/mmcblk0
            FSBL_SEEK=$((1536 * 1024))
            ENV=/dev/mmcblk0
            ENV_SEEK=$((640 * 1024))
            UBOOT=/dev/mmcblk0
            # 以KB为单位
            UBOOT_SEEK=8192
            ;;
        "/dev/mmcblk2"*)
            BOOTINFO_FILE=bootinfo_block.bin
            BOOTINFO=/dev/mmcblk2
            BOOTINFO_SEEK=$((1024 * 1024))
            FSBL=/dev/mmcblk2
            FSBL_SEEK=$((1536 * 1024))
            ENV=/dev/mmcblk2
            ENV_SEEK=$((640 * 1024))
            UBOOT=/dev/mmcblk2
            # 以KB为单位
            UBOOT_SEEK=8192
            ;;
        "/dev/sda"*)
            BOOTINFO_FILE=bootinfo_block.bin
            BOOTINFO=/dev/sda
            BOOTINFO_SEEK=$((1024 * 1024))
            FSBL=/dev/sda
            FSBL_SEEK=$((1536 * 1024))
            ENV=/dev/sda
            ENV_SEEK=$((640 * 1024))
            UBOOT=/dev/sda
            # 以KB为单位
            UBOOT_SEEK=8192
            ;;
        "/dev/nvme0n1"*)
            if [ -e "/dev/mtdblock6" ]; then
                BOOTINFO_FILE=bootinfo_spinor.bin
                BOOTINFO=/dev/mtdblock1
                FSBL=/dev/mtdblock2
                FSBL_SEEK=0
                ENV=/dev/mtdblock3
                ENV_SEEK=0
                UBOOT=/dev/mtdblock6
                # 以KB为单位
                UBOOT_SEEK=0
            elif [ -e "/dev/mtdblock0" ]; then
                BOOTINFO_FILE=bootinfo_spinor.bin
                BOOTINFO=/dev/mtdblock0
                BOOTINFO_SEEK=0
                FSBL=/dev/mtdblock0
                FSBL_SEEK=$((128 * 1024))
                ENV=/dev/mtdblock0
                ENV_SEEK=$((640 * 1024))
                UBOOT=/dev/mtdblock0
                # 以KB为单位
                UBOOT_SEEK=2112
            else
                # emmc + ssd
                BOOTINFO_FILE=bootinfo_block.bin
                BOOTINFO=/dev/mmcblk2
                BOOTINFO_SEEK=$((1024 * 1024))
                FSBL=/dev/mmcblk2
                FSBL_SEEK=$((1536 * 1024))
                ENV=/dev/mmcblk2
                ENV_SEEK=$((640 * 1024))
                UBOOT=/dev/mmcblk2
                # 以KB为单位
                UBOOT_SEEK=2112
            fi
            ;;
        *)
            echo "Unsupported root=$ROOT"
            exit 1
            ;;
        esac
    else
        echo "Missing root= in cmdline"
        exit 1
    fi

    BIN_DIR="/usr/lib/u-boot/$target"
    # 待检查文件列表
    files="${BIN_DIR}/${BOOTINFO_FILE} ${BIN_DIR}/FSBL.bin ${BIN_DIR}/env.bin ${BIN_DIR}/u-boot.itb $BOOTINFO $FSBL $ENV $UBOOT"
    for file in $files; do
        if [ ! -e "$file" ]; then
            # 任意不存在则退出
            echo "Missing $file"
            exit 1
        fi
    done

    # 此前已经做了所有检查
    set -x
    if [ -n "$BOOTINFO_SEEK" ]; then
        dd if=/usr/lib/u-boot/$target/$BOOTINFO_FILE of=$BOOTINFO seek=$BOOTINFO_SEEK bs=1 && sync
    else
        dd if=/usr/lib/u-boot/$target/$BOOTINFO_FILE of=$BOOTINFO && sync
    fi
    dd if=/usr/lib/u-boot/$target/FSBL.bin of=$FSBL seek=$FSBL_SEEK bs=1 && sync
    dd if=/usr/lib/u-boot/$target/env.bin of=$ENV seek=$ENV_SEEK bs=1 && sync
    dd if=/usr/lib/u-boot/$target/u-boot.itb of=$UBOOT seek=$UBOOT_SEEK bs=1K && sync
    set +x
    ;;
esac

exit 0
