#!/bin/sh
set -e

case "$1" in
configure)
    target=""
    if grep -q '^spacemit' /sys/firmware/devicetree/base/model; then
        target="spacemit"
    else
        exit 0
    fi

    for x in $(cat /proc/cmdline); do
        case $x in
        root=*)
            ROOT=${x#root=}
            ;;
        esac
    done

    if [ -n $ROOT ]; then
        case $ROOT in
        "/dev/mmcblk0"*)
            BOOTINFO=/dev/mmcblk0
            FSBL=/dev/mmcblk0p1
            UBOOT=/dev/mmcblk0p4
            ;;
        "/dev/mmcblk2"*)
            BOOTINFO=/dev/mmcblk2boot0
            FSBL=/dev/mmcblk2boot0
            UBOOT=/dev/mmcblk2p4
            if [ -e $BOOTINFO ]; then
                echo 0 | tee /sys/block/mmcblk2boot0/force_ro
            else
                exit 0
            fi
            ;;
        *)
            echo "Unsupported root=$ROOT"
            exit 0
            ;;
        esac
    else
        echo "Missing root= in cmdline"
        exit 0
    fi

    if [ -n "$target" ] && [ -e $BOOTINFO ] && [ -e $FSBL ] && [ -e $UBOOT ]; then
        dd if=/usr/lib/u-boot/$target/bootinfo_emmc.bin of=$BOOTINFO && sync
        dd if=/usr/lib/u-boot/$target/FSBL.bin of=$FSBL seek=512 bs=1 && sync
        dd if=/usr/lib/u-boot/$target/u-boot.itb of=$UBOOT bs=1M && sync
    fi
    ;;
esac

exit 0
