#!/bin/bash -e
# ---------------------------------------------------------------------------
# regen_pubkey_dtsi.sh  --  regenerate a key dtsi from a public key
#
# Method:
#   mkimage -f <min.its> -K <empty.dtb> -k <KEYDIR> -r    # writes pubkey into dtb
#   dtc -I dtb -O dts <empty.dtb>                         # decompile -> dts
# The /signature/key-<hint> node from the decompiled dts IS the dtsi body.
# The -r flag is MANDATORY (without required="conf" the node is emitted.
#
# Usage:
#   regen_pubkey_dtsi.sh <hint> <key_dir> <out_dtsi> [mkimage]
#     <hint>     key-name-hint, e.g. kernel_key_prv / uboot_key_prv
#                (KEY_DIR must contain <hint>.key and <hint>.crt)
#     <key_dir>  directory holding <hint>.key + <hint>.crt
#     <out_dtsi> destination .dtsi to overwrite
#     [mkimage]  optional mkimage path (default: search PATH)
# ---------------------------------------------------------------------------

HINT="$1"
KEYDIR="$2"
OUT_DTSI="$3"
MK="${4:-}"

die() { echo "[regen-dtsi][ERROR] $*" >&2; exit 1; }

[ -n "$HINT" ] && [ -n "$KEYDIR" ] && [ -n "$OUT_DTSI" ] || \
    die "usage: $0 <hint> <key_dir> <out_dtsi> [mkimage]"
[ -f "$KEYDIR/$HINT.key" ] || die "missing $KEYDIR/$HINT.key"
[ -f "$KEYDIR/$HINT.crt" ] || die "missing $KEYDIR/$HINT.crt (needed for pubkey params)"

# locate mkimage
if [ -z "$MK" ]; then
    if command -v mkimage >/dev/null 2>&1; then MK="$(command -v mkimage)";
    else die "mkimage not found (pass as 4th arg)"; fi
fi
command -v dtc >/dev/null 2>&1 || die "dtc not found"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# minimal ITS: one dummy fdt image + one config requiring a signature so
# mkimage -K exports the pubkey (with required="conf") into the -K dtb.
head -c 256 /dev/urandom > "$WORK/dummy.bin"
cat > "$WORK/min.its" <<ITS
/dts-v1/;
/ {
    description = "pubkey-export";
    #address-cells = <1>;
    images {
        fdt-1 {
            data = /incbin/("./dummy.bin");
            type = "flat_dt";
            arch = "riscv";
            compression = "none";
            hash-1 { algo = "sha256"; };
        };
    };
    configurations {
        default = "conf-1";
        conf-1 {
            fdt = "fdt-1";
            signature-1 {
                algo = "sha256,rsa2048";
                key-name-hint = "$HINT";
                sign-images = "fdt";
            };
        };
    };
};
ITS

echo "/dts-v1/; / { };" | dtc -O dtb -o "$WORK/empty.dtb" 2>/dev/null

( cd "$WORK" && "$MK" -f min.its -K empty.dtb -k "$KEYDIR" -r out.itb >/dev/null 2>&1 ) \
    || die "mkimage -K failed (check $HINT.key/.crt in $KEYDIR)"

# decompile and extract the /signature/key-<hint> node, wrap it in the dtsi
# skeleton that matches the shipped files.
DECOMP="$WORK/decomp.dts"
dtc -I dtb -O dts "$WORK/empty.dtb" 2>/dev/null > "$DECOMP" \
    || die "dtc decompile failed"

grep -q "key-$HINT" "$DECOMP" || die "pubkey node key-$HINT not found in export"

NODE_BODY="$(awk "
    /key-$HINT[[:space:]]*\{/ { inblk=1; next }
    inblk && /^[[:space:]]*};[[:space:]]*\$/ { inblk=0 }
    inblk { print }
" "$DECOMP")"

[ -n "$NODE_BODY" ] || die "failed to extract key-$HINT node body"

{
    echo "// SPDX-License-Identifier: (GPL-2.0 OR MIT)"
    echo "/* Copyright (c) 2023 Spacemit, Inc */"
    echo "/* Regenerated by regen_pubkey_dtsi.sh from $HINT public key */"
    echo "/ {"
    echo "	signature {"
    echo "		key-$HINT {"
    echo "$NODE_BODY"
    echo "		};"
    echo "	};"
    echo "};"
} > "$OUT_DTSI"

echo "[regen-dtsi] wrote $OUT_DTSI (hint=$HINT)"
grep -o "rsa,modulus = <0x[0-9a-f]*" "$OUT_DTSI" | head -1
